# Generated by Django 5.0 on 2023-12-11 15:51
from uuid import uuid4
from django.db import migrations


def forward_func(apps, schema_editor):
    TicketModel = apps.get_model("order", "Ticket")
    count = 0
    ticket_list = []
    while count < 1000000:
        count += 1
        ticket_list.append(TicketModel(token=uuid4()))

    TicketModel.objects.bulk_create(ticket_list)


def reverse_func(apps, schema_editor):
    TicketModel = apps.get_model("order", "Ticket")
    TicketModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]
