# Generated by Django 5.0 on 2023-12-13 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_generate_fake_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRegeneratingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
